---
# ServiceAccount para ejecutar pipelines
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline-sa
  namespace: default

---
# INSTRUCCIONES PARA CREAR SECRET DE DOCKER HUB
# 
# Opción 1: Crear cuenta GRATIS en Docker Hub
# 1. Ve a https://hub.docker.com y crea una cuenta
# 2. Luego ejecuta este comando con tus credenciales:
#
# kubectl create secret docker-registry dockerhub-credentials \
#   --docker-server=docker.io \
#   --docker-username=TU_USUARIO \
#   --docker-password=TU_PASSWORD \
#   --docker-email=TU_EMAIL \
#   -n default
#

---
# Role para deploy en Kubernetes
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-pipeline-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "pods/log"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create", "delete"]

---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipeline-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-pipeline-role
subjects:
  - kind: ServiceAccount
    name: tekton-pipeline-sa
    namespace: default

---
# ClusterRole para lectura de recursos del cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipeline-clusterrole
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["tekton.dev"]
    resources: ["tasks", "pipelines", "pipelineruns", "taskruns"]
    verbs: ["get", "list", "create", "update", "patch"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipeline-clusterbinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-pipeline-clusterrole
subjects:
  - kind: ServiceAccount
    name: tekton-pipeline-sa
    namespace: default

